#
# This is a hello world HOT template just defining a single compute
# server.
#
heat_template_version: 2014-10-16

description: >
  Hello world HOT template that just defines a single server.
  Contains just base features to verify base HOT support.

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    default: TP3-Typhoon
    constraints:
      - custom_constraint: nova.keypair
  flavor:
    type: string
    description: Flavor for the server to be created
    default: INF4410-mini
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    description: Image ID or image name to use for the server
    default: INF4410-Ubuntu-trusty-mini
    constraints:
      - custom_constraint: glance.image
  net_id:
    type: string
    description: Network
    default: inf4410-net
    constraints:
      - custom_constraint: neutron.network
    #A completer
  floating_ip_uuid:
    type: string
    description: Floating IP id to be used by the instance
    default: d4d78786-6ff7-4ea5-a3f5-932cbc99a030
    


resources:
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - network: { get_param: net_id }
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        wget https://raw.githubusercontent.com/houssemmh/INF4410-TP3/master/server.py
        python server.py

  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_param: floating_ip_uuid }
      server_id: { get_resource: server }
  

